import Head from 'next/head';
import Header from '@/components/Header';
import Body from '@/components/Body';
import Footer from '@/components/Footer';
import StyledComponentsRegistry from '@/lib/registry';

export default function Home() {
  return (
    <>
      <Head>
        <title>Libro</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Body />
      <Footer />
    </>
  );
}
