'use client';

import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import Header from '@/components/Header';
import Body from '@/components/Body';
import Footer from '@/components/Footer';
import { ToastContainer } from 'react-toastify';
import { RecoilRoot } from 'recoil';

export default function Home() {
  return (
    <>
      <Head>
        <title>Libro</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <RecoilRoot>
        <Header />
        <Body />
        <Footer />
        <ToastContainer />
      </RecoilRoot>
    </>
  );
}
